name: CI

on: [push, pull_request]

jobs:
  in-docker_test:
    runs-on: ubuntu-18.04
    container:
      image: openjdk:8-jdk-alpine
      volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    steps:
    - uses: actions/checkout@v1
    - name: Build with Gradle
      run: ./gradlew --no-daemon --continue --scan testcontainers:check --tests '*GenericContainerRuleTest'
