name: CI

on: [push, pull_request]

jobs:
  in-docker_test:
    runs-on: ubuntu-18.04
    container:
      image: openjdk:8-jdk-alpine
      options: "--workdir /home/runner/work"
      volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/home/runner/:/home/runner/"
    steps:
    - uses: actions/checkout@v1
    - name: Build with Gradle
      run: |
        cd "/home/runner/work/${{ github.repository }}"
        pwd
        ./gradlew --no-daemon --continue --scan testcontainers:test --tests '*GenericContainerRuleTest'
