name: CI

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        tasks:
        - "testcontainers:test --tests org.testcontainers.junit.DockerComposeContainerWithBuildTest"
        jdk: ["1.8"]
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.jdk }}
    - name: Build with Gradle
      run: ./gradlew --no-daemon --continue --scan --info ${{ matrix.tasks }}
  in-docker_test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Build with Gradle
      run: |
        docker run -i --rm \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -v "$HOME:$HOME" \
          -v "$PWD:$PWD" \
          -w "$PWD" \
          openjdk:8-jdk-alpine \
          ./gradlew --no-daemon --continue --scan testcontainers:test --tests '*GenericContainerRuleTest'

