name: CI

on: [push, pull_request]

jobs:
  in-docker_test:
    runs-on: ubuntu-18.04
    container:
      image: openjdk:8-jdk-alpine
      options: "--workdir /home/runner/work/${{ github.repository }}"
      volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/home/runner/work/${{ github.repository }}/:/home/runner/work/${{ github.repository }}/"
    steps:
    - uses: actions/checkout@v1
    - name: Build with Gradle
      run: |
        pwd
        ls -la
        ls -la /home/runner/work/
        cd "/home/runner/work/${{ github.repository }}"
        pwd
        ./gradlew --no-daemon --continue --scan testcontainers:test --tests '*GenericContainerRuleTest'
